package kubeila.employee.entity;

public class SysUsersRoles {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_users_roles.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_users_roles.user_id
     *
     * @mbggenerated
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_users_roles.role_id
     *
     * @mbggenerated
     */
    private Long roleId;

    private String rolename;

    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_users_roles.id
     *
     * @return the value of sys_users_roles.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_users_roles.id
     *
     * @param id the value for sys_users_roles.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_users_roles.user_id
     *
     * @return the value of sys_users_roles.user_id
     *
     * @mbggenerated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_users_roles.user_id
     *
     * @param userId the value for sys_users_roles.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_users_roles.role_id
     *
     * @return the value of sys_users_roles.role_id
     *
     * @mbggenerated
     */
    public Long getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_users_roles.role_id
     *
     * @param roleId the value for sys_users_roles.role_id
     *
     * @mbggenerated
     */
    public void setRoleId(Long roleId) {
        this.roleId = roleId;
    }

    public String getRolename() {
        return rolename;
    }

    public void setRolename(String rolename) {
        this.rolename = rolename;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }
}