package kubeila.employee.dao.mapper;

import java.util.List;
import kubeila.employee.entity.SysRolesPermissions;
import kubeila.employee.entity.SysRolesPermissionsExample;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface SysRolesPermissionsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_roles_permissions
     *
     * @mbggenerated
     */
    int countByExample(SysRolesPermissionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_roles_permissions
     *
     * @mbggenerated
     */
    int deleteByExample(SysRolesPermissionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_roles_permissions
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_roles_permissions
     *
     * @mbggenerated
     */
    int insert(SysRolesPermissions record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_roles_permissions
     *
     * @mbggenerated
     */
    int insertSelective(SysRolesPermissions record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_roles_permissions
     *
     * @mbggenerated
     */
    List<SysRolesPermissions> selectByExample(SysRolesPermissionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_roles_permissions
     *
     * @mbggenerated
     */
    SysRolesPermissions selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_roles_permissions
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") SysRolesPermissions record, @Param("example") SysRolesPermissionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_roles_permissions
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") SysRolesPermissions record, @Param("example") SysRolesPermissionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_roles_permissions
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SysRolesPermissions record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_roles_permissions
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SysRolesPermissions record);
}