package kubeila.employee.dao.mapper;

import java.util.List;
import kubeila.employee.entity.SysUsersRoles;
import kubeila.employee.entity.SysUsersRolesExample;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface SysUsersRolesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_users_roles
     *
     * @mbggenerated
     */
    int countByExample(SysUsersRolesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_users_roles
     *
     * @mbggenerated
     */
    int deleteByExample(SysUsersRolesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_users_roles
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_users_roles
     *
     * @mbggenerated
     */
    int insert(SysUsersRoles record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_users_roles
     *
     * @mbggenerated
     */
    int insertSelective(SysUsersRoles record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_users_roles
     *
     * @mbggenerated
     */
    List<SysUsersRoles> selectByExample(SysUsersRolesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_users_roles
     *
     * @mbggenerated
     */
    SysUsersRoles selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_users_roles
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") SysUsersRoles record, @Param("example") SysUsersRolesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_users_roles
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") SysUsersRoles record, @Param("example") SysUsersRolesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_users_roles
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SysUsersRoles record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_users_roles
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SysUsersRoles record);


    List<SysUsersRoles> selectUserstoRole(SysUsersRoles record);
}